import uuid

from locust import HttpUser, between, tag, task


class TaskManagerUser(HttpUser):
    wait_time = between(1, 3)

    def on_start(self):
        suffix = uuid.uuid4().hex[:8]
        self.login = f"load-user-{suffix}"
        self.password = "password123"
        self.headers = {}

        self.client.post(
            "/auth/register",
            json={"login": self.login, "password": self.password},
            name="/auth/register",
        )

        login_response = self.client.post(
            "/auth/login",
            data={"username": self.login, "password": self.password},
            name="/auth/login",
        )
        access_token = login_response.json()["access_token"]
        self.headers = {"Authorization": f"Bearer {access_token}"}

        for _ in range(3):
            self.create_task()

    def create_task(self):
        task_suffix = uuid.uuid4().hex[:6]
        self.client.post(
            "/tasks",
            json={
                "title": f"Task {task_suffix}",
                "description": "Generated by Locust",
                "status": "pending",
                "priority": 1,
            },
            headers=self.headers,
            name="/tasks [POST]",
        )

    @tag("mixed")
    @task(1)
    def create_new_task(self):
        self.create_task()

    @tag("read-heavy")
    @task(4)
    def list_tasks(self):
        self.client.get(
            "/tasks",
            headers=self.headers,
            name="/tasks [GET default]",
        )

    @tag("read-heavy", "mixed")
    @task(2)
    def list_filtered_tasks(self):
        self.client.get(
            "/tasks",
            params={"search": "Task", "sort_by": "created_at", "limit": 10},
            headers=self.headers,
            name="/tasks [GET filtered]",
        )
